### ISSUE TITLE
Choose a cloud platform 

### ISSUE THREAD

**Issue by iradche** [IPMITMO/EXYJO#10]

**Comment by alexclear** [comment]
Please provide a set of criteria
(Maybe we should add a separate task to develop this set)

**Comment by VladaDem** [comment]
Azure

**Comment by iradche** [comment]
https://startpack.ru/application/cloud9/alternatives

**Comment by VladaDem** [comment]
Доброй ночи! Я открыла Вам доступ к эссе для Потанинской стипендии.
Пожалуйста, посмотрите.

С уважением, Влада.

2016-10-31 20:16 GMT+03:00 Irina Radchenko notifications@github.com:
